language: node_js
node_js:
 - "10.8.0"
script:
  - npm test
services:
  - postgresql
  before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run codeclimate-report