language: node_js
node_js:
 - "10.8.0"
addon:
  code_climate:
     repo_token: 19fe087efc8cce3c903638c3e4fd175df9471050a8d99df5fbfed4f623c1ac51
script: istanbul cover npm test -- -R spec
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
